zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null # 也可以设置 glob 规则列表，例如：["2026/survey/**","2026/reading-group/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: ${oc.env:MODEL}
  language: Chinese

source:
  arxiv:
    category: ["cond-mat"]

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']

reranker:
  local:
    encode_kwargs:
      batch_size: 4

hugo:
  output_dir: ${oc.env:HUGO_OUTPUT_DIR,null}
  auto_push: true
